#!/bin/bash

rm -rf lib
mkdir lib
mkdir lib/esm
mkdir lib/cjs
mkdir lib/types

rollup -c rollup-config.js
tsc \
  --emitDeclarationOnly \
  --declarationDir lib/types \
  --declarationMap \
  --mapRoot src
