#!/bin/bash

BRANCH=$(git rev-parse --abbrev-ref HEAD)
DIFF=$(git diff HEAD)
ROOT=$(git rev-parse --show-toplevel)

if [[ -n $DIFF ]]; then

  echo 'There are unstaged changed, please commit changes before publishing'
  exit 1

fi

if [[ -z $npm_package_version ]]; then

  echo 'Unable to determine package version to publish'
  exit 1

fi

cd $ROOT

git fetch -p
git checkout main

DIFF=$(git diff HEAD)

if [[ -n $DIFF ]]; then

  echo 'There are unstaged changed, please commit changes before publishing'
  exit 1

fi


yarn lint

if [[ $? != 0 ]]; then
  echo
  echo "Fix yo lint errors"
  echo
  exit 1
fi

yarn build

if [[ $? != 0 ]]; then
  echo
  echo "Unsuccessful build... Bailing"
  echo
  exit 1
fi

yarn jest

if [[ $? != 0 ]]; then
  echo
  echo "Unsuccessful tests... Bailing"
  echo
  exit 1
fi

yarn publish --access public --new-version $npm_package_version

git push
# pushes the tag
git push origin $VERSION

git checkout $BRANCH
git merge main --no-edit
git push
